# Copyright lowRISC contributors (OpenTitan project).
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

load("//rules:otbn.bzl", "otbn_library")

package(default_visibility = ["//visibility:public"])

otbn_library(
    name = "ntt_base_dilithium",
    srcs = [
        "ntt_base_dilithium.s",
    ],
)

otbn_library(
    name = "intt_base_dilithium",
    srcs = [
        "intt_base_dilithium.s",
    ],
)

otbn_library(
    name = "ntt_mldsa",
    srcs = [
        "ntt_mldsa.s",
    ],
)

otbn_library(
    name = "ntt_mldsa_exp_reduction",
    srcs = [
        "ntt_mldsa_exp_reduction.s",
    ],
)

otbn_library(
    name = "intt_mldsa",
    srcs = [
        "intt_mldsa.s",
    ],
)

otbn_library(
    name = "intt_mldsa_exp_reduction",
    srcs = [
        "intt_mldsa_exp_reduction.s",
    ],
)
